---
kind: pipeline
type: docker
name: CI/CD

steps:
  - name: test
    image: golang
    environment:
      CODECOV_TOKEN:
        from_secret: codecov_slug
    commands:
      - go get github.com/matryer/moq
      - make cover
      - bash -c 'bash <(curl -s https://codecov.io/bash)'

  - name: build
    image: golang
    commands:
      - mkdir build
      - go build -o build/did ./did/

  - name: lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - build/did
      title: ${DRONE_TAG}
    when:
      event: tag
