language: go
go:
  - '1.10'

dist: trusty
sudo: false

install:
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/GetStream/vg
  - 'eval "$(vg eval --shell bash)"'
  - vg init
  - make all

script:
  - if [ -z "$TRAVIS_TAG" ]; then travis_wait make cover; else make test; fi

after_success:
   - bash <(curl -s https://codecov.io/bash) -t 009c6129-4454-4732-9004-d3f6376d89c5
